-- Syntax-highlighter generator. Single source of truth: the keyword set is
-- extracted from lang/parser.lua's `keywords` table, so it can never drift from
-- the real lexer. Types/constants are the highlight palette (the lexer treats
-- any identifier as a type in declaration position, so those aren't a lexer
-- keyword set -- we list the primitives editors should colour).
-- Run from the project root:  lua5.4 tools/genhl.lua
local PARSER = "lang/parser.lua"
local OUTDIR = "editors"

-- pull the reserved words out of parser.lua's `keywords = { ["x"]=true, ... }`
local function read_keywords()
  local fh = assert(io.open(PARSER, "r"))
  local src = fh:read("*a"); fh:close()
  local block = src:match("local keywords = (%b{})")
  if not block then error("could not find the keywords table in " .. PARSER) end
  local words = {}
  for w in block:gmatch('%["(%a+)"%]%s*=%s*true') do words[#words + 1] = w end
  return words
end

local keywords = read_keywords()
local extra_kw = {"as"}             -- contextual: a name in the lexer, a keyword to the eye
local types = {"int", "float", "str", "string", "char", "bool", "void"}
local constants = {"true", "false", "null"}

local function join(list, sep) return table.concat(list, sep or " ") end
local function alternation(list) return "(" .. join(list, "|") .. ")" end

local function write(path, body)
  local fh = assert(io.open(path, "w"))
  fh:write(body); fh:close()
  print("wrote " .. path)
end

os.execute("mkdir -p " .. OUTDIR)

-- ---- Vim (classic vimscript regex syntax) -------------------------------
local function gen_vim()
  local kw = {}
  for _, w in ipairs(keywords) do kw[#kw + 1] = w end
  for _, w in ipairs(extra_kw) do kw[#kw + 1] = w end
  local lines = {
    '" Vim syntax for Nova -- generated by tools/genhl.lua, do not edit',
    'if exists("b:current_syntax") | finish | endif',
    "",
    "syn keyword novaKeyword " .. join(kw),
    "syn keyword novaType " .. join(types),
    "syn keyword novaConstant " .. join(constants),
    [[syn match  novaChar "'\\\?.'"]],
    'syn match  novaNumber "\\<\\d\\+\\(\\.\\d\\+\\)\\?\\>"',
    'syn match  novaFunction "\\<\\h\\w*\\ze\\s*("',
    'syn match  novaOperator "[-+*/%=<>!&|^~?:]"',
    -- comments/strings LAST so they out-prioritise the operator at // and ";
    -- regions with contains=NONE absorb their text, so operators and keywords
    -- inside them are not re-highlighted
    'syn region novaComment start="//" end="$" contains=NONE',
    'syn region novaComment start="/\\*" end="\\*/" contains=NONE',
    'syn region novaString start=+"+ skip=+\\\\"+ end=+"+ contains=NONE',
    "",
    "hi def link novaKeyword  Keyword",
    "hi def link novaType     Type",
    "hi def link novaConstant Constant",
    "hi def link novaComment  Comment",
    "hi def link novaString   String",
    "hi def link novaChar     Character",
    "hi def link novaNumber   Number",
    "hi def link novaFunction Function",
    "hi def link novaOperator Operator",
    "",
    'let b:current_syntax = "nova"',
    "",
  }
  write(OUTDIR .. "/nova.vim", join(lines, "\n"))
  write(OUTDIR .. "/ftdetect_nova.vim",
    'au BufRead,BufNewFile *.nova set filetype=nova\n')
end

-- ---- micro (YAML regex syntax) ------------------------------------------
local function gen_micro()
  local kw = {}
  for _, w in ipairs(keywords) do kw[#kw + 1] = w end
  for _, w in ipairs(extra_kw) do kw[#kw + 1] = w end
  local lines = {
    "# Nova syntax for micro -- generated by tools/genhl.lua, do not edit",
    "filetype: nova",
    "",
    "detect:",
    '    filename: "\\\\.nova$"',
    "",
    "rules:",
    '    - type: "\\\\b' .. alternation(types) .. '\\\\b"',
    '    - statement: "\\\\b' .. alternation(kw) .. '\\\\b"',
    '    - constant: "\\\\b' .. alternation(constants) .. '\\\\b"',
    '    - constant.number: "\\\\b[0-9]+(\\\\.[0-9]+)?\\\\b"',
    -- micro uses Go RE2 (no lookahead), so no clean "name before (" rule;
    -- function names render as default text.
    '    - symbol.operator: "[-+*/%=<>!&|^~?:]"',
    "",
    "    - constant.string:",
    '        start: "\\""',
    '        end: "\\""',
    '        skip: "\\\\."',
    "        rules: []",
    "",
    "    - comment:",
    '        start: "//"',
    '        end: "$"',
    "        rules: []",
    "",
    "    - comment:",
    '        start: "/\\\\*"',
    '        end: "\\\\*/"',
    "        rules: []",
    "",
  }
  write(OUTDIR .. "/nova.yaml", join(lines, "\n"))
end

gen_vim()
gen_micro()
print(string.format("keywords (%d, from %s): %s",
  #keywords, PARSER, join(keywords, ", ")))
